name: Build and Push Docker Image to Docker Hub 
on:
  push:
    branches:
      - Feature/Docker-image

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        image_name: ["binge-plus-be"]

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io # Optional, good practice to be explicit
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest